name: 'Infra Gitops Action'
description: 'Action to facilitate the Gitops workflow at Skillz'
author: 'Skillz Infra Team<devops@skillz.com>'
inputs:
  valueFile:
    required: true
    description: 'YAML file which should be updated'
  propertyPath:
    required: true
    description: 'Property Path in the yaml file - using dot for nesting: e.g. backend.version'
    default: 'imageTag'
  value:
    required: true
    description: 'New property value'
  branch:
    required: true
    description: 'Branch to commit the change, will be created if not exist'
  targetBranch:
    required: false
    description: 'Target Branch for the created PullRequest'
    default: master
  message:
    required: false
    description: 'Commit message for the value update'
    default: ''
  title:
    required: false
    description: 'Title of the created pull request'
    default: ''
  description:
    required: false
    description: 'Description of the created pull request'
    default: ''
  labels:
    required: false
    description: 'Comma separated list of custom PR labels, e.g. "feature,yaml-updates"'
    default: 'ci-update'
  token:
    required: false
    description: 'GitHub AuthToken for Athorization'
    default: ${{ github.token }}
  repository:
    required: false
    description: 'repoistory to update'
    default: ${{ github.repository }}
  workDir:
    required: false
    description: 'repository workspace location'
    default: apps
runs:
  using: 'node12'
  main: 'dist/index.js'
